#!/usr/bin/env node
// Copies the browser builds of Chart.js and ExcelJS into vendor/ so the app
// runs offline (including straight from file://), and embeds the CBRE logos
// as base64 for the Excel export. Run after `npm install`: `npm run vendor`.
'use strict';

const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '..');
const nm = path.join(root, 'node_modules');
const vendor = path.join(root, 'vendor');
fs.mkdirSync(vendor, { recursive: true });

const copies = [
  ['chart.js/dist/chart.umd.min.js', 'chart.umd.min.js'],
  ['chart.js/LICENSE.md', 'chart.js.LICENSE.md'],
  ['exceljs/dist/exceljs.min.js', 'exceljs.min.js'],
  ['exceljs/LICENSE', 'exceljs.LICENSE'],
];
for (const [from, to] of copies) {
  fs.copyFileSync(path.join(nm, from), path.join(vendor, to));
  console.log(`vendor/${to}`);
}

const versions = {
  'chart.js': require(path.join(nm, 'chart.js/package.json')).version,
  exceljs: require(path.join(nm, 'exceljs/package.json')).version,
};
fs.writeFileSync(path.join(vendor, 'VERSIONS.json'), JSON.stringify(versions, null, 2) + '\n');
console.log('vendor/VERSIONS.json', versions);

const logo = (file) => 'data:image/png;base64,' + fs.readFileSync(path.join(root, 'assets', file)).toString('base64');
const brandAssets = `// Generated by scripts/vendor.js. Do not edit by hand.
(function (root) {
  'use strict';
  root.CBRE_LOGOS = {
    green: '${logo('cbre-logo-green.png')}',
    white: '${logo('cbre-logo-white.png')}',
  };
})(typeof self !== 'undefined' ? self : this);
`;
fs.writeFileSync(path.join(root, 'js', 'logos.js'), brandAssets);
console.log('js/logos.js');
